# Generated by Django 3.1.7 on 2021-03-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='employess_list',
            field=models.ManyToManyField(related_name='participants', to='meetings.Employee'),
        ),
    ]
