# Generated by Django 3.1.7 on 2021-03-17 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="employess_list",
        ),
        migrations.AddField(
            model_name="reservation",
            name="employees",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
