# Generated by Django 3.1.7 on 2021-03-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20210317_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
