# Generated by Django 3.1.7 on 2021-05-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
