# Generated by Django 3.1.7 on 2021-08-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20210808_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='room_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
