# Generated by Django 3.1.7 on 2021-07-09 08:50

from django.db import migrations, models


def fill_meetings_rooms(apps, model_class):
    MeetingRoom = apps.get_model('meetings', 'MeetingRoom')
    default_room = 'IT'
    for room in MeetingRoom.objects.all():
        room.country = default_room
        room.save()


class Migration(migrations.Migration):
    dependencies = [
        ('meetings', '0002_reservation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='testing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(fill_meetings_rooms, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='meetingroom',
            name='testing',
            field=models.CharField(max_length=100),
        ),
    ]
