# Generated by Django 3.1.7 on 2021-05-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='employess_list',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
