# Generated by Django 3.1.7 on 2021-07-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingroom_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='testing2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='testing',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
